### PR TITLE
#169649350 Add homepage info

### PR DESCRIPTION
**Pull request by neelxie**
### What the PR does?
- Add viable information on the landing page
- Add application contact

### How to test it?
- pull the branch
- run `php artisan serve`
- control-click on the link in the terminal and go to the browser.

### Pivotal Tracker Story
[#169649350](https://www.pivotaltracker.com/story/show/169649350)

### CODE REVIEW

**Review by NicholusMuwonge — CHANGES_REQUESTED** [review]
@neelxie, great work and please add an image to your description. Thanks

**Comment by neelxie** [comment]
> @neelxie, great work and please add an image to your description. Thanks

@NicholusMuwonge Sadly I am unable to, no guideline whatsoever require screenshots for every PR if I am not conforming to any guidelines by not adding screenshots kindly share those guidelines with me here, if it was a consensus then it could have been documented, kindly share with me the doc; be it team guidelines or development best practices. I feel screenshots are for lazy people that do not want to test the application. And thank you again for your feedback.

**Comment by NicholusMuwonge** [comment]
> > @neelxie, great work and please add an image to your description. Thanks
> 
> @NicholusMuwonge Sadly I am unable to, no guideline whatsoever require screenshots for every PR if I am not conforming to any guidelines by not adding screenshots kindly share those guidelines with me here, if it was a consensus then it could have been documented, kindly share with me the doc; be it team guidelines or development best practices. I feel screenshots are for lazy people that do not want to test the application. And thank you again for your feedback.

Hey @neelxie, this is definitely frustrating for you but reviewing each other's work should be made simple. You have noticed I added screenshots for every feature I did and so did the rest. I think that shows its not just laziness but helping out the people who will review your code to have a nicer time doing it as they also usually have their own work to worry about. So I would recommend to include it usually just like we used to at Andela. Thanks.

**Comment by neelxie** [comment]
> > > @neelxie, great work and please add an image to your description. Thanks
> > 
> > 
> > @NicholusMuwonge Sadly I am unable to, no guideline whatsoever require screenshots for every PR if I am not conforming to any guidelines by not adding screenshots kindly share those guidelines with me here, if it was a consensus then it could have been documented, kindly share with me the doc; be it team guidelines or development best practices. I feel screenshots are for lazy people that do not want to test the application. And thank you again for your feedback.
> 
> Hey @neelxie, this is definitely frustrating for you but reviewing each other's work should be made simple. You have noticed I added screenshots for every feature I did and so did the rest. I think that shows its not just laziness but helping out the people who will review your code to have a nicer time doing it as they also usually have their own work to worry about. So I would recommend to include it usually just like we used to at Andela. Thanks.

@NicholusMuwonge Kindly re-read my prior response for clarity. You have a responded with a subjective personal opinion or stance because of what you did which is wrong, to say the least. If our team work-flow is going to be based on your personal preferred instances then this is wrong because that would mean that the entirety of our workflow would be unsustainable because it would be based on your preference per occurrence. For best team practices I kindly suggest we as a team collectively agree on them and document them, then and only then can we occasionally use them as a  reference where workflow does not conform to the set guidelines. 
To put it plainly; my PR and everything about it conforms and exceeds the requirements for quality work if you think it is falling short or erring a particular rule or guideline then kindly share it here and I will gladly make the changes if not put this issue to rest.

Your own PR did not conform to the standards you are setting for others, kindly confirm that and approve this PR thank you.

**Review by reifred — CHANGES_REQUESTED** [review]
Thank you @neelxie for the work done. But this is not a feature. It's a bug fix because you are updating but not adding new functionality. Kindly rename this branch to follow coding conventions(For example this branch name would be like fix-landing-page-info)

**Pull request closed without merging**
