### PR TITLE
feat(Reset): Reset Password

### PR DESCRIPTION
**Pull request by neelxie**
### What the PR does?
- Set up email credentials
- Design relevant forms

### How to test it?
- pull the branch
- run `php artisan serve`
- control-click on the link in the terminal and go to the browser.
- Click `Forgot Password?` on the Login Page
- Fill in your email address and check your email for a reset password link
- Click the link that takes you to a new form to fill in your new password 

### Screenshots

The reset password form
firsts

The sent email
emailss

The new password
formss

### Pivotal Tracker Story
[#168950160](https://www.pivotaltracker.com/story/show/168950160)

### CODE REVIEW

**Review by HabibSentongo — COMMENTED** [review]
Thanks for the good work. Kindly add some screenshots of the forms in the PR description.

**Comment by neelxie** [comment]
> Thanks for the good work. Kindly add some screenshots of the forms in the PR description.

This has been worked on @HabibSentongo

**Review by NicholusMuwonge — CHANGES_REQUESTED** [review]
Hey @neelxie, I get this error when I try to reset password
greatest

**Comment by NicholusMuwonge** [comment]
Hey derrick I get this error when I try to reset my password

**Comment by neelxie** [comment]
> Hey @neelxie, I get this error when I try to reset password
> greatest

I have added details for the .env that requires all the app to run perfectly.

**Review by HabibSentongo — COMMENTED** [review]
Kindly put all the necessary env variables in the `.env.example` file instead of on the PR description as you've done.
image
only point out the need to update them if you know you have added some in the example file.

**Comment by neelxie** [comment]
> Kindly put all the necessary env variables in the `.env.example` file instead of on the PR description as you've done.
> image
> only point out the need to update them if you know you have added some in the example file.

@HabibSentongo this has been fixed.

**Review by HabibSentongo — APPROVED** [review]

**Review by reifred — APPROVED** [review]

**Review by NicholusMuwonge — APPROVED** [review]

**Pull request merged**
