### PR TITLE
#168950106 Add Email Verification on User Registration

### PR DESCRIPTION
**Pull request by HabibSentongo**
### What the PR does?
- add verify middleware in the constructor of the home controller
- make user class require an email verification process
- add email verification route in the web.php file

### How to test it?
- pull the branch
- run `php artisan serve`
- Control-click on the link in the terminal and go to the browser.
- Click on the `Get Started Now` button and signup. Or try to login with your old credentials that don't have a verified email.

### Pivotal Tracker Story
[#168950106](https://www.pivotaltracker.com/story/show/168950106)

### screenshots

image

image

image

### CODE REVIEW

**Comment by NicholusMuwonge** [comment]
Hello habib, thanks for the great work, let me look into the code and pull it down for testing

**Review by neelxie — APPROVED** [review]
@HabibSentongo Good work on this, keep it up, If you can kindly can spare a moment to add a description to your Task on the story board to give me insight on what your task is all about.

**Comment by HabibSentongo** [comment]
> @HabibSentongo Good work on this, keep it up, If you can kindly spare a moment to add a description to your Task on the storyboard to give me insight on what your task is all about.

Thank you for your review and approval @neelxie, I'll get to that shortly.

**Review by reifred — COMMENTED** [review]
Thanks, @HabibSentongo for the good work. Kindly address @neelxie's comment so that I can approve this PR.

**Comment by HabibSentongo** [comment]
Thank you @reifred for your review. I have worked on your feedback, kindly look into it.

**Review by NicholusMuwonge — CHANGES_REQUESTED** [review]
Hey @habib, when I try to set up I get this error, Is there like some setup you didn't include in the description?

pic_render

**Comment by NicholusMuwonge** [comment]
Also on that `click here to request another` button according to description screenshots needs some padding and I think the button will look better when its bigger

**Comment by HabibSentongo** [comment]
> Also on that `click here to request another` button according to description screenshots needs some padding and I think the button will look better when its bigger

Kindly note that that is not a button but rather just highlighted regular hyperlinked text that is a continuation of the sentence that starts above.

**Comment by HabibSentongo** [comment]
> Hey @habib, when I try to set up I get this error, Is there like some setup you didn't include in the description?
> 
> pic_render

@NicholusMuwonge kindly note that this doesn't require any new configurations. It uses the exact email settings that the old emailing features have been using.
If you look closely in your error message it shows you that you have your env config vars wrong, you have `companyemail` as a var value instead of the actual email address.

**Review by reifred — APPROVED** [review]

**Review by NicholusMuwonge — APPROVED** [review]

**Pull request merged**
